Repository boostcampwm2023/web13_Boarlog, pull requests merged in 2023-11, with the labels that each got.

#95 Feature(#1): npm 초기화 및 vite 설치
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: FE, ⚙ env

#96 Feature(#4): backend 프로젝트 초기 설정 및 style 적용
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: BE, ⚙ env

#97 Feature(#2, #3): 프론트엔드 환경설정(eslint, prettier, tailwind, recoil)
  frontend/.eslintrc.cjs
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/tailwind.config.js
Labels: FE, ⚙ Env

#98 Feature(#5): backend CI/CD 파이프라인 구축
  .github/workflows/github_actions_cd.yml
  .github/workflows/github_actions_ci.yml
  backend/.dockerignore
  backend/Dockerfile
Labels: BE, ⚙ Env

#100 Feature(#99): eslint-import-resolver-alias 라이브러리 설치
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
Labels: FE, ⚙ Env

#102 Fix(#5): 도커 이미지 빌드 에러 해결
  backend/Dockerfile
Labels: 🐞 Fix, BE

#103 Feature(#101): route 설정, Tailwind CSS 기본 설정, 스캐폴드 구성
  frontend/.eslintrc.cjs
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/1.md
  frontend/src/assets/react.svg
  frontend/src/components/Header.tsx
  frontend/src/global.css
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Home/components/1.md
  package-lock.json
Labels: FE, ⚙ Env

#104 Feature(#101): svgr 초기 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/vite.config.ts
  package-lock.json
Labels: FE, ⚙ Env

#106 Feature(#105): TailwindCSS 기본 theme 설정, svg/img 파일 업로드, favicon 설정
  frontend/index.html
  frontend/package-lock.json
  frontend/public/favicon.ico
  frontend/src/App.tsx
  frontend/src/assets/1.md
  frontend/src/assets/imgs/joinLecture.png
  frontend/src/assets/imgs/logoBig.png
  frontend/src/assets/imgs/logoSmall.png
  frontend/src/assets/imgs/newLecture.png
  frontend/src/assets/svgs/calendar.svg
  frontend/src/assets/svgs/close.svg
  frontend/src/assets/svgs/google.svg
  frontend/src/assets/svgs/home.svg
  frontend/src/assets/svgs/micOff.svg
  frontend/src/assets/svgs/micOn.svg
  frontend/src/assets/svgs/newLecture.svg
  frontend/src/assets/svgs/play.svg
  frontend/src/assets/svgs/setting.svg
  frontend/src/assets/svgs/share.svg
  frontend/src/assets/svgs/stop.svg
  frontend/src/assets/svgs/user.svg
  frontend/src/global.css
  frontend/src/pages/Home/Home.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: FE, ⚙ Env

#107 Feature(#7): login 페이지 UI 프로토타입 구현
  frontend/src/App.tsx
  frontend/src/global.css
  frontend/src/pages/Login/Login.tsx
  frontend/src/pages/Login/components/Header.tsx
  frontend/src/pages/Login/components/LoginSection.tsx
Labels: ✨ Feat, FE

#108 Fix: package-lock.json 업데이트
  frontend/package-lock.json
Labels: 🐞 Fix, FE

#109 Feature(#50): 화이트보드 펜 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/_redirects
  frontend/src/App.tsx
  frontend/src/assets/svgs/whiteboard/alignCenter.svg
  frontend/src/assets/svgs/whiteboard/alignLeft.svg
  frontend/src/assets/svgs/whiteboard/alignRight.svg
  frontend/src/assets/svgs/whiteboard/delete.svg
  frontend/src/assets/svgs/whiteboard/eraser.svg
  frontend/src/assets/svgs/whiteboard/image.svg
  frontend/src/assets/svgs/whiteboard/mouse.svg
  frontend/src/assets/svgs/whiteboard/palette.svg
  frontend/src/assets/svgs/whiteboard/pen.svg
  frontend/src/assets/svgs/whiteboard/speakerNotes.svg
  frontend/src/assets/svgs/whiteboard/stickyNote.svg
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Login/Login.tsx
  frontend/src/pages/Test/Test.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/Header.tsx
Labels: ✨ Feat, FE

#111 Fix(#110) Test 페이지 TypeScript 오류 해결
  frontend/src/pages/Test/components/CanvasSection.tsx
Labels: 🐞 Fix, FE

#112 Refactor(#50): 화이트보드 코드 리팩토링, hand mode(드래그로 화면 움직이기)기능 추가
  frontend/src/assets/svgs/whiteboard/hand.svg
  frontend/src/global.css
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/ToolButton.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
Labels: 🛠️ Refactor, FE

#116 Feature(#60): 사용자 정보 모달 UI 작업
  frontend/package-lock.json
  frontend/src/assets/imgs/profileMedium.png
  frontend/src/assets/imgs/profileSmall.png
  frontend/src/assets/svgs/enter.svg
  frontend/src/assets/svgs/logout.svg
  frontend/src/assets/svgs/user.svg
  frontend/src/components/Header.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/LeftSection.tsx
  frontend/src/components/Header/components/ProfileModal.tsx
  frontend/src/components/Header/components/RightSection.tsx
  frontend/src/pages/Home/Home.tsx
Labels: ✨ Feat, FE

#117 Feature(#62): Header 컴포넌트 navigate 추가
  frontend/src/App.tsx
  frontend/src/components/Header/components/LeftSection.tsx
  frontend/src/components/Header/components/ProfileModal.tsx
  frontend/src/pages/MyPage/MyPage.tsx
Labels: ✨ Feat, FE

#118 Feature(#51): 선의 색상을 변경할 수 있다.
  frontend/src/App.tsx
  frontend/src/assets/svgs/check.svg
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/ColorPanel.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/stateCanvasInstance.ts
  frontend/tailwind.config.js
Labels: ✨ Feat, FE

#119 Feature(#64): 강의자 Header component UI 구성
  frontend/src/assets/svgs/micOff.svg
  frontend/src/assets/svgs/micOn.svg
  frontend/src/assets/svgs/play.svg
  frontend/src/assets/svgs/setting.svg
  frontend/src/assets/svgs/stop.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderLecturerControls.tsx
  frontend/src/components/Header/components/HeaderLoginButton.tsx
  frontend/src/components/Header/components/HeaderLogo.tsx
  frontend/src/components/Header/components/HeaderMainButtons.tsx
  frontend/src/components/Header/components/HeaderProfileButton.tsx
  frontend/src/components/Header/components/HeaderProfileModal.tsx
  frontend/src/components/Header/components/HeaderSettingButton.tsx
  frontend/src/components/Header/components/HeaderSettingModal.tsx
  frontend/src/components/Header/components/RightSection.tsx
  frontend/src/components/SmallButton/SmallButton.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/MyPage/MyPage.tsx
Labels: ✨ Feat, FE

#113 Feature(#8 #114): 회원가입 및 구글 로그인
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/userInfo.dto.ts
  backend/src/auth/google.strategy.ts
  backend/src/schema/user.schema.ts
Labels: BE, ⚙ Env

#120 Feature(#26): 양방향 통신 기능 적용 & WebRTC 연결을 위한 서버 로직 추가
  .gitignore
  mediaServer/.eslintrc.js
  mediaServer/.gitignore
  mediaServer/.prettierrc
  mediaServer/package-lock.json
  mediaServer/package.json
  mediaServer/src/RelayServer.ts
  mediaServer/src/main.ts
  mediaServer/test/commons/css/main.css
  mediaServer/test/commons/js/streamVisualizer.js
  mediaServer/test/presenter/index.html
  mediaServer/tsconfig.json
Labels: ✨ Feat, BE

#123 Feature(#67,#69): 입력장치 선택, 음성 파형 및 강의 진행시간 헤더에 표시
  frontend/src/App.tsx
  frontend/src/components/Header/components/HeaderLecturerControls.tsx
  frontend/src/components/Header/components/HeaderSettingModal.tsx
  frontend/src/components/Header/components/VolumeMeter.tsx
  frontend/src/components/Header/components/stateMicrophone.tsx
  frontend/src/pages/MicTest/MicTest.tsx
  frontend/src/pages/MicTest/components/AudioRecord.tsx
  frontend/src/pages/MicTest/components/Header.tsx
Labels: ✨ Feat, FE

#124 Feature(#122): Button, Modal 공용 컴포넌트 개발
  frontend/src/App.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Header/components/HeaderLecturerControls.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/global.css
  frontend/src/pages/Example/Example.tsx
  frontend/src/pages/Home/Home.tsx
Labels: ✨ Feat, FE

#125 Fix: 미디어 서버에서 클라이언트 MediaStream 정상적으로 받지 못하는 문제 해결
  mediaServer/src/RelayServer.ts
  mediaServer/test/presenter/index.html
Labels: 🐞 Fix, BE

#127 Feature(#34) 발표자 음성 미디어 서버 전달 프로토타입
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header/components/HeaderSettingModal.tsx
  frontend/src/pages/MicTest/MicTest.tsx
  frontend/src/pages/MicTest/components/AudioRecord.tsx
Labels: ✨ Feat, FE

#129 Feature(#34) 발표자 헤더를 통해 음성을 미디어 서버로 전달
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderLecturerControls.tsx
  frontend/src/components/Header/components/HeaderSettingModal.tsx
  frontend/src/pages/MicTest/components/AudioRecord.tsx
  mediaServer/src/RelayServer.ts
Labels: ✨ Feat, FE

#130 Feature(#133): Toast 공용 컴포넌트 구현
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/assets/svgs/toast/alert.svg
  frontend/src/assets/svgs/toast/default.svg
  frontend/src/assets/svgs/toast/success.svg
  frontend/src/components/Header/components/HeaderLogo.tsx
  frontend/src/components/Toast/ToastContainer.tsx
  frontend/src/components/Toast/constants.ts
  frontend/src/components/Toast/toastAtom.ts
  frontend/src/components/Toast/toastType.ts
  frontend/src/components/Toast/usePortal.ts
  frontend/src/components/Toast/useToast.ts
  frontend/src/global.css
  frontend/src/pages/Example/Example.tsx
  frontend/tailwind.config.js
  netlify.toml
Labels: ✨ Feat, FE

#132 Feature(#67) 설정 모달에서 발표자 마이크 음량을 설정할 수 있다.
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderSettingModal.tsx
  frontend/src/components/Header/components/stateMicVolme.tsx
  frontend/src/pages/MicTest/components/AudioRecord.tsx
  mediaServer/src/RelayServer.ts
Labels: ✨ Feat, FE

#134 Feature(#49): 포스트잇 색, 글꼴 편집 기능 구현
  frontend/src/assets/svgs/L.svg
  frontend/src/assets/svgs/M.svg
  frontend/src/assets/svgs/S.svg
  frontend/src/assets/svgs/XL.svg
  frontend/src/assets/svgs/check.svg
  frontend/src/assets/svgs/deleteMemo.svg
  frontend/src/assets/svgs/formatAlignCenter.svg
  frontend/src/assets/svgs/formatAlignLeft.svg
  frontend/src/assets/svgs/formatAlignRight.svg
  frontend/src/assets/svgs/palette.svg
  frontend/src/assets/svgs/whiteboard/eraser.svg
  frontend/src/assets/svgs/whiteboard/image.svg
  frontend/src/assets/svgs/whiteboard/stickyNote.svg
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/StickyNoteColorPanel.tsx
  frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/getStickyNoteInstance.ts
  frontend/src/pages/Test/components/stateStickyNoteEditPanelVisible.ts
  frontend/src/pages/Test/components/stateStickyNoteInstance.ts
  frontend/tailwind.config.js
Labels: ✨ Feat, 🛠️ Refactor, FE

#131 Feature(#27) 강의실 생성 API 구현
  backend/.prettierrc
  backend/src/app.module.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.module.ts
  backend/src/room/room.schema.ts
  backend/src/room/room.service.ts
  backend/src/utils/GenerateUtils.ts
Labels: ✨ Feat, BE

#137 Feature(#136): 마이페이지 API 구현
  backend/src/app.module.ts
  backend/src/auth/dto/userInfo.dto.ts
  backend/src/lecture/lecture.module.ts
  backend/src/lecture/lecture.schema.ts
  backend/src/main.ts
  backend/src/schema/user.schema.ts
  backend/src/user/dto/username.update.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
Labels: ✨ Feat, BE

#140 Feature: DB에서 참여 코드 관리 & 강의실 입장 시 해당 유저의 수강한 강의 목록에 추가
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/dto/enter-room.dto.ts
  backend/src/room/room-code.schema.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.module.ts
  backend/src/room/room.service.ts
  backend/src/user/dto/user.update.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: ✨ Feat, BE

#143 Fix(#142): 캔버스 클릭 후 메모 클릭시 글꼴 초기화 되는 문제 해결
  frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
  frontend/src/pages/Test/components/stateStickyNoteInstance.ts
Labels: 🐞 Fix, FE

#141 Fix(#138) 서버 연결 후 마이크 입력 장치 변경 반영되도록 수정
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
Labels: 🐞 Fix, FE

#150 Fix(#149) 배포환경에서 MediaStream 참여자가 못 받는 문제 수정
  mediaServer/package-lock.json
  mediaServer/package.json
  mediaServer/src/RelayServer.ts
  mediaServer/src/main.ts
  mediaServer/test/presenter/index.html
  mediaServer/test/student/index.html
Labels: 🐞 Fix, BE

#151 Feature(#16): 메인 페이지 UI 구현
  frontend/src/assets/svgs/enter.svg
  frontend/src/assets/svgs/newLecture.svg
  frontend/src/assets/svgs/search.svg
  frontend/src/global.css
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Home/components/1.md
  frontend/src/pages/Home/components/JoinLectureBack.tsx
  frontend/src/pages/Home/components/JoinLectureFront.tsx
  frontend/src/pages/Home/components/LectureCodeInput.tsx
  frontend/src/pages/Home/components/MainCard.tsx
  frontend/src/pages/Home/components/NewLectureBack.tsx
  frontend/src/pages/Home/components/NewLectureFront.tsx
  frontend/tailwind.config.js
  netlify.toml
Labels: ✨ Feat, FE

#147 Feat(#66,#73,#74) 강의자 음성 음소거, 참여자 헤더 UI 구현
  frontend/src/App.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderInstructorSettingModal.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/HeaderParticipantSettingModal.tsx
  frontend/src/components/Header/components/HeaderSettingButton.tsx
  frontend/src/pages/Instructor/Instructor.tsx
  frontend/src/pages/Instructor/components/AudioRecord.tsx
  frontend/src/pages/Instructor/components/Header.tsx
  frontend/src/pages/MicTest/MicTest.tsx
  frontend/src/pages/Participant/Participant.tsx
Labels: ✨ Feat, FE

#152 Feature(#68): 강의 코드 공유 버튼 구현
  frontend/index.html
  frontend/public/thumnail.png
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderCodeCopyButton.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Toast/ToastContainer.tsx
Labels: ✨ Feat, FE

#154 Feature(#48): 메모의 텍스트를 수정 기능 구현
  frontend/package-lock.json
  frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/getStickyNoteInstance.ts
  frontend/src/pages/Test/components/stateStickyNoteInstance.ts
Labels: ✨ Feat, FE

#153 Feature(#115): 로그아웃을 할 수 있다.
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.guard.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/google.strategy.ts
  backend/src/main.ts
Labels: ✨ Feat, BE

#157 Feature(#30, #45, #87, #146, #156): 미디어 서버에서 여러 강의실을 관리하고, 화이트보드 & 질문 & 강의 종료 & 강의 나가기를 지원한다
  mediaServer/package-lock.json
  mediaServer/package.json
  mediaServer/src/RelayServer.ts
  mediaServer/src/main.ts
  mediaServer/src/models/ClientInfo.ts
  mediaServer/src/models/Message.ts
  mediaServer/src/models/RoomInfo.ts
  mediaServer/src/pc.config.ts
  mediaServer/test/presenter/index.html
  mediaServer/test/student/index.html
Labels: ✨ Feat, BE

#158 Feature(#92): 지우개 모드 기능 구현
  frontend/src/assets/svgs/eraserMouseCursor.svg
  frontend/src/pages/Test/components/ColorPanel.tsx
  frontend/src/pages/Test/components/StickyNoteColorPanel.tsx
  frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
Labels: ✨ Feat, FE

#159 Feat(#58,#71,#72) 참여자 페이지 음성 스트리밍 구현, 음량 및 스피커 조절
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderInstructorSettingModal.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/HeaderParticipantSettingModal.tsx
  frontend/src/components/Header/components/stateSelectedMicrophone.tsx
  frontend/src/components/Header/components/stateSelectedSpeaker.tsx
  frontend/src/components/Header/components/stateSpeakerVolme.tsx
  mediaServer/test/commons/css/main.css
Labels: ✨ Feat, FE

#155 Feature(#10): 초기 정보 입력 페이지 UI 구현, 닉네임 컨벤션 확인
  frontend/src/App.tsx
  frontend/src/assets/imgs/profileBig.png
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderLogo.tsx
  frontend/src/pages/Login/Login.tsx
  frontend/src/pages/Login/components/LoginSection.tsx
  frontend/src/pages/Start/Start.tsx
  frontend/src/pages/Start/components/StartSection.tsx
  frontend/tailwind.config.js
Labels: ✨ Feat, FE

#164 Feature(#43 #44) 화이트보드 공유 구현
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/HeaderParticipantSettingModal.tsx
  frontend/src/components/Header/components/stateSpeakerVolme.tsx
  frontend/src/components/Header/components/stateSpeakerVolume.tsx
  frontend/src/pages/Participant/Participant.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/stateCanvasRef.tsx
  frontend/src/pages/Test/components/stateVideoRef.tsx
  mediaServer/test/student/index.html
Labels: ✨ Feat, FE

#167 주소 수정
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: ✨ Feat, FE

#166 Feature(#55, #56, #57, #145): 질문 리스트 버튼 및 인디케이터 버블, 질문 리스트 UI, 기능 구현
  frontend/public/dummyQuestionData.json
  frontend/src/assets/svgs/whiteboard/add.svg
  frontend/src/assets/svgs/whiteboard/question.svg
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/QuestionButton.tsx
  frontend/src/pages/Test/components/QuestionList.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/getStickyNoteInstance.ts
  frontend/src/pages/Test/components/stateActiveTool.ts
  frontend/src/pages/Test/components/stateClickedQuestionContents.ts
  frontend/src/pages/Test/components/stateIsQuestionListOpen.ts
  frontend/src/pages/Test/components/stateQuestionCount.ts
Labels: ✨ Feat, FE

#169 Feature(#76): 마이 페이지 UI 작업, 반응형 추가 작업
  frontend/src/App.tsx
  frontend/src/assets/svgs/calendar.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderCodeCopyButton.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderInstructorSettingModal.tsx
  frontend/src/components/Header/components/HeaderLogo.tsx
  frontend/src/components/Header/components/HeaderMainButtons.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/HeaderParticipantSettingModal.tsx
  frontend/src/components/Header/components/HeaderProfileModal.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Home/components/JoinLectureBack.tsx
  frontend/src/pages/Home/components/JoinLectureFront.tsx
  frontend/src/pages/Home/components/LectureCodeInput.tsx
  frontend/src/pages/Home/components/MainCard.tsx
  frontend/src/pages/Home/components/NewLectureBack.tsx
  frontend/src/pages/Home/components/NewLectureFront.tsx
  frontend/src/pages/Login/Login.tsx
  frontend/src/pages/Login/components/Header.tsx
  frontend/src/pages/Login/components/LoginSection.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/MyPage/components/MyPageSection.tsx
  frontend/src/pages/MyPage/components/ReplayLectureCard.tsx
  frontend/src/pages/Start/Start.tsx
  frontend/src/pages/Start/components/StartSection.tsx
  frontend/tailwind.config.js
Labels: ✨ Feat, FE

#174 Feature: 글자가 개행됨에 따라 메모지 크기 조절 기능 구현 #172
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/getStickyNoteInstance.ts
Labels: ✨ Feat, FE

#175 Feature(#65) 디버깅 버튼 제거, 강의 시작시 알림 모달을 띄워 다시 확인
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: ✨ Feat, FE
