Repository boostcampwm2023/web13_Boarlog, pull requests merged in 2023-12, with the labels that each got.

#181 Feature(#180): 발표자의 영상과 음성 스트림을 파일로 저장
  mediaServer/.gitignore
  mediaServer/src/RelayServer.ts
  mediaServer/src/config/ffmpeg.config.ts
  mediaServer/src/config/pc.config.ts
  mediaServer/src/models/FfmpegCommand.ts
  mediaServer/src/models/PeerStreamInfo.ts
  mediaServer/src/utils/MediaConverter.ts
  mediaServer/test/commons/css/main.css
  mediaServer/test/presenter/index.html
  mediaServer/test/student/index.html
Labels: ✨ Feat, BE

#179 Fix(#177, #178): 화이트보드(지우개, 메모지) 관련 버그 수정
  frontend/src/pages/Test/components/Toolbar.tsx
Labels: 🐞 Fix, 🛠️ Refactor, FE

#184 Fix(#183) 강의 참여시 곧바로 발표자의 화이트보드가 보이도록 개선
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: 🐞 Fix, FE

#189 Feature(#188): Axios 라이브러리 설치
  frontend/package-lock.json
  frontend/package.json
Labels: FE, ⚙ Env

#191 Feature(#24): Error 페이지, 강의 종료 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/imgs/endLecture.png
  frontend/src/assets/svgs/home.svg
  frontend/src/pages/ErrorPage/ErrorPage.tsx
  frontend/src/pages/LectureEnd/LectureEnd.tsx
  package-lock.json
Labels: ✨ Feat, FE

#192 Feature(#42): 강의 참여 페이지 채팅 사이드바를 사용자가 확인할 수 있다 (UI 작업)
  frontend/src/assets/svgs/sendMessage.svg
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/global.css
  frontend/src/pages/Participant/Participant.tsx
Labels: ✨ Feat, FE

#197 Feature(#196): 참여자가 강의실 입장 시 강의 시작시간 전달
  mediaServer/src/RelayServer.ts
  mediaServer/src/models/RoomInfo.ts
Labels: ✨ Feat, BE

#198 Refactor: API 요청 관련 URL env 처리
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: 🛠️ Refactor, FE

#200 Feature(#69) 참여자 페이지 강의 시간 확인, 강의 코드에 맞춰서 강의실 생성/입장 구현
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/LogContainer/LogContainer.tsx
Labels: ✨ Feat, FE

#199 Feature(#59, #161) 발표자 미디어 파일 Object Storage에 저장, DB에 강의 정보 업데이트
  mediaServer/package-lock.json
  mediaServer/package.json
  mediaServer/src/config/ncp.config.ts
  mediaServer/src/models/FfmpegCommand.ts
  mediaServer/src/utils/ncp-storage.ts
Labels: ✨ Feat, BE

#203 Feature(#202): 화이트보드 변경내역 추가 API 구현
  backend/src/lecture/dto/response-lecture-info.dto.ts
  backend/src/lecture/dto/whiteboard-event.dto.ts
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.module.ts
  backend/src/lecture/lecture.service.ts
  backend/src/lecture/schema/lecture-code.schema.ts
  backend/src/lecture/schema/lecture.schema.ts
  backend/src/lecture/schema/whiteboard-log.schema.ts
  backend/src/user/user.schema.ts
Labels: ✨ Feat, BE

#206 Feature(#204): 질문 채팅창을 버튼 토글을 이용해 숨기고 보여줄 수 있다.
  frontend/src/assets/svgs/close.svg
  frontend/src/pages/Participant/Participant.tsx
  frontend/src/pages/Participant/components/QuestionLogButton.tsx
  frontend/src/stores/stateIsQuestionLogOpen.ts
Labels: ✨ Feat, FE

#210 Feature(#39, #43, #44, #207) socket 통신으로 화이트보드 공유 구현
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/pages/Participant/Participant.tsx
  frontend/src/pages/Participant/ParticipantVideoVer.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/stores/stateParticipantCanvasInstance.ts
Labels: ✨ Feat, 🛠️ Refactor, FE

#219 Feature(#31, #36) 강의가 종료되면 강의자와 참여자 페이지 모두에게 강의 종료 페이지로 이동
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/pages/Participant/Participant.tsx
  frontend/src/pages/Participant/ParticipantVideoVer.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
Labels: ✨ Feat, FE

#214 Feature(#79): 클로바 API를 사용하여 음성을 글로 추출하고 자막으로 DB에 저장한다.
  backend/src/lecture/interfaces/Subtitle.ts
  backend/src/lecture/lecture-subtitle.schema.ts
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.module.ts
  backend/src/lecture/lecture.service.ts
Labels: ✨ Feat, BE

#221 Feature(#220): 강의실 입장 시 현 시점 화이트보드 데이터 전달
  mediaServer/src/RelayServer.ts
  mediaServer/src/models/RoomInfo.ts
Labels: ✨ Feat, BE

#224 Fix: NCP에 파일 업로드 시 mp3 확장자로 저장될 수 있도록 확장자 변경
  mediaServer/src/utils/ncp-storage.ts
Labels: 🐞 Fix, BE

#225 Refact/231207 new question focus
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/QuestionButton.tsx
  frontend/src/pages/Test/components/QuestionList.tsx
  frontend/src/utils/convertMsToTimeString.ts
Labels: 🛠️ Refactor, FE

#227 Refector : 강의코드 강의자,참여자 페이지에 반영, 화이트보드 공유 과정 안정화
  frontend/src/assets/svgs/play.svg
  frontend/src/assets/svgs/progressPause.svg
  frontend/src/assets/svgs/progressPlay.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderCodeCopyButton.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderInstructorSettingModal.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/VolumeMeter.tsx
  frontend/src/components/Toast/useToast.ts
  frontend/src/pages/Review/components/ProgressBar.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/stateCanvasRef.tsx
  frontend/src/stores/stateMicVolme.tsx
  frontend/src/stores/stateMicVolume.ts
  frontend/src/stores/stateMicVolumeGain.ts
Labels: 🛠️ Refactor, FE

#226 Refactor(#217): 화이트보드-backspace로 그래픽 요소 지우기 구현
  frontend/src/pages/Test/components/CanvasSection.tsx
Labels: 🛠️ Refactor, FE

#229 Feature(#17, #19, #20, #21, #205): home 페이지 API 연동, modernizr 적용
  frontend/global.d.ts
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Toast/useToast.ts
  frontend/src/global.d.ts
  frontend/src/main.tsx
  frontend/src/modernizr.js
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Home/components/JoinLectureBack.tsx
  frontend/src/pages/Home/components/NewLectureBack.tsx
  frontend/tsconfig.json
Labels: ✨ Feat, FE

#231 fix: 소켓 연결을 일찍 닫아버리는 문제 및 참여자 페이지 소켓 연결 순서 변경
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: 🔥 Hotfix, FE

#235 Refactor: 로그인 방식 변경
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.guard.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.signin.dto.ts
  backend/src/auth/dto/auth.signup.dto.ts
  backend/src/auth/dto/userInfo.dto.ts
  backend/src/auth/google.strategy.ts
  backend/src/lecture/lecture.service.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.schema.ts
  backend/src/utils/GenerateUtils.ts
Labels: 🛠️ Refactor, BE

#233 Refactor: 강의자/참여자 헤더 리팩토링
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/fabricCanvasUtil.ts
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/utils/calcNormalizedVolume.ts
  frontend/src/utils/convertMsToTimeString.ts
Labels: 🛠️ Refactor, FE

#238 Refactor: ResponseDto 추가 및 코드컨벤션 적용
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/response-signin.dto.ts
  backend/src/auth/dto/sign-in.dto.ts
  backend/src/auth/dto/sign-up.dto.ts
  backend/src/user/dto/update-user.dto.ts
  backend/src/user/user.controller.ts
Labels: 🛠️ Refactor, BE

#239 Feature(#236): 로그인/회원가입 페이지 작업
  frontend/src/App.tsx
  frontend/src/assets/imgs/logoOriginal.png
  frontend/src/assets/imgs/subLogoOriginal.png
  frontend/src/pages/Login/Login.tsx
  frontend/src/pages/Login/components/LoginSection.tsx
  frontend/src/pages/UserAuth/UserAuth.tsx
  frontend/src/pages/UserAuth/components/UserAuthSection.tsx
Labels: ✨ Feat, FE

#241 Feat(#209, #240) 다시보기 페이지 프로그래스바 및 프롬프트 기능 구현
  frontend/public/reviewLecture.json
  frontend/src/assets/svgs/progressPlay.svg
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
  frontend/src/stores/stateProgressMsTime.ts
  frontend/src/utils/converTimeStringToMS.ts
  frontend/src/utils/convertMsToTimeString.ts
Labels: ✨ Feat, FE

#246 Refactor(#242): 미디어 서버 역할 분리하기
  mediaServer/package-lock.json
  mediaServer/package.json
  mediaServer/src/RelayServer.ts
  mediaServer/src/config/redis.config.ts
  mediaServer/src/constants/client-type.constant.ts
  mediaServer/src/constants/redis-key.constant.ts
  mediaServer/src/dto/client-info.dto.ts
  mediaServer/src/dto/room-info.dto.ts
  mediaServer/src/interfaces/canvas-data.interface.ts
  mediaServer/src/models/ClientConnectionInfo.ts
  mediaServer/src/models/RoomConnectionInfo.ts
  mediaServer/src/models/RoomInfo.ts
  mediaServer/src/services/client.service.ts
  mediaServer/src/services/room.service.ts
Labels: 🛠️ Refactor, BE

#245 Refactor: 강의 조회 API 및 마이페이지 내 정보 조회 API 수정
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/google.strategy.ts
  backend/src/lecture/dto/response-lecture-info.dto.ts
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.module.ts
  backend/src/lecture/lecture.service.ts
  backend/src/main.ts
  backend/src/user/dto/lectureInfo.dto.ts
  backend/src/user/dto/presenterInfo.dto.ts
  backend/src/user/dto/update-user.dto.ts
  backend/src/user/dto/userInfo.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.schema.ts
  backend/src/user/user.service.ts
Labels: 🛠️ Refactor, BE

#248 Feat: 강의 다시보기 API 구현
  backend/src/lecture/dto/response/response-lecture-info.dto.ts
  backend/src/lecture/dto/response/response-lecture-record.dto.ts
  backend/src/lecture/dto/whiteboard-event.dto.ts
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.service.ts
  backend/src/lecture/schema/whiteboard-log.schema.ts
Labels: ✨ Feat, BE

#250 Refactor(#249): 링크 공유 개선, Toast state 분리
  frontend/src/components/Header/components/HeaderCodeCopyButton.tsx
  frontend/src/components/Toast/ToastContainer.tsx
  frontend/src/components/Toast/useToast.ts
  frontend/src/stores/stateToastList.ts
Labels: 🛠️ Refactor, FE

#251 Refactor: 강의 조회와 내 프로필 조회 API 분리
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.service.ts
  backend/src/user/dto/userInfo.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: 🛠️ Refactor, BE

#252 Feature(#82,#83,#84,#85) 화이트보드 다시보기 구현
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/fabricCanvasUtil.ts
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/pages/Participant/ParticipantVideoVer.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
  frontend/src/utils/fabricCanvasUtil.ts
Labels: ✨ Feat, FE

#255 Refactor: 강의생성 API 로그인 된 사용자만 호출하도록 수정
  backend/src/auth/auth.controller.ts
  backend/src/lecture/dto/create-lecture.dto.ts
  backend/src/lecture/lecture.controller.ts
Labels: 🛠️ Refactor, BE

#257 Refactor: 로그인할 때 응답 형식 변경
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/response-signin.dto.ts
Labels: 🛠️ Refactor, BE

#253 Feature(#243): 발표자 재접속 시 미해결 질문 & 화이트보드 정보 & 강의 시작시간 전달
  mediaServer/src/RelayServer.ts
  mediaServer/src/constants/redis-key.constant.ts
  mediaServer/src/dto/room-info.dto.ts
  mediaServer/src/main.ts
  mediaServer/src/services/client.service.ts
  mediaServer/src/services/question-service.ts
  mediaServer/src/services/room.service.ts
  mediaServer/src/services/socket.service.ts
  mediaServer/src/types/canvas-data.interface.ts
  mediaServer/src/types/redis-stream.type.ts
  mediaServer/src/validation/request.validation.ts
Labels: ✨ Feat, BE

#259 Feature(#81,#86) 프로그래스바 음성 출력 구현
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
Labels: ✨ Feat, FE

#258 Fix(#254): home 페이지 강의 생성/조회 API 수정
  frontend/src/components/Header/components/HeaderProfileModal.tsx
  frontend/src/hooks/useAuth.ts
  frontend/src/pages/Home/components/NewLectureBack.tsx
  frontend/src/pages/UserAuth/components/UserAuthSection.tsx
Labels: 🐞 Fix, FE

#260 Feature(#256): 프로그래스바 드래그 기능 구현
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
Labels: ✨ Feat, FE

#261 refact: 컨플릭트 해결 과정에서 실수한 부분 해결
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
Labels: 🐞 Fix, FE

#264 Fix(#262): 발표자 연결 수립 과정에서 화이트보드 초기 데이터 받을 수 있도록 구성
  mediaServer/src/RelayServer.ts
  mediaServer/src/dto/room-info.dto.ts
Labels: 🐞 Fix, BE

#265 FIX: 새로 방을 개설했을 때만, 강의 시작시간과 화이트보드 초기 데이터 반영
  mediaServer/src/RelayServer.ts
  mediaServer/src/services/client.service.ts
Labels: 🐞 Fix, BE

#266 Fix(#215) 발표자가 강의를 나갔다가 들어오는 경우 (새로고침 등) 강의를 계속 할 수 있게 한다.
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderLogo.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/utils/fabricCanvasUtil.ts
Labels: 🐞 Fix, FE

#267 hotfix: 참여자 페이지 게스트 토큰 임시 추가
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: 🔥 Hotfix, FE

#270 feature(#215) 강의자가 새로고침 후 재접속 해도 음성이 잘 들리도록 개선
  mediaServer/src/RelayServer.ts
Labels: 🐞 Fix, BE

#275 feature: 참여자가 socket id 전송하도록 개선
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
Labels: FE

#277 Fix(#272, #274, #276): 피드백에서 제보된 메모 관련 문제 해결
  frontend/public/vite.svg
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/QuestionList.tsx
  frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/getStickyNoteInstance.ts
  frontend/src/pages/Test/components/stateClickedQuestionContents.ts
  frontend/src/pages/Test/components/stateQuestionList.ts
  frontend/src/stores/stateIsMemoEditing.ts
Labels: 🐞 Fix, 🛠️ Refactor, FE

#269 Feature(#268): 발표자 페이지 새로고침 시 해결되지 않은 질문 리스트 백업 기능 구현
  frontend/public/vite.svg
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
  frontend/src/pages/Test/components/QuestionList.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
  frontend/src/pages/Test/components/stateClickedQuestionContents.ts
  frontend/src/pages/Test/components/stateQuestionList.ts
Labels: ✨ Feat, FE

#273 Feat(#271): 질문 id와 solved 요청을 받으면, 해당 질문에 ACK 요청을 보낸다.
  mediaServer/src/RelayServer.ts
Labels: ✨ Feat, BE

#279 Feature: 미디어서버에서 API 서버로 요청 보내기
  mediaServer/src/RelayServer.ts
  mediaServer/src/models/FfmpegCommand.ts
  mediaServer/src/utils/MediaConverter.ts
Labels: ✨ Feat, BE

#281 Feature(#278): Enter keydown event 추가
  frontend/src/pages/UserAuth/components/UserAuthSection.tsx
Labels: ✨ Feat, FE

#282 Fix: 발표자에게 질문 전달 시 questionId가 정상적으로 전달이 안되는 부분 수정
  mediaServer/src/RelayServer.ts
  mediaServer/src/dto/asked.request.dto.ts
Labels: 🐞 Fix, BE

#283 Refactor: API requestDTO 형식 수정
  backend/src/lecture/dto/whiteboard-event.dto.ts
  backend/src/lecture/lecture.service.ts
  backend/src/lecture/schema/whiteboard-log.schema.ts
Labels: 🛠️ Refactor, BE

#284 Fix: 리뷰 페이지 개선, 볼륨 바 남아있는 에러 해결
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/components/Header/components/HeaderReviewButtons.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/components/ProgressBar.tsx
Labels: 🐞 Fix, FE

#285 Fix(#280): 캔버스 관련 이슈
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/pages/Test/components/CanvasSection.tsx
Labels: 🐞 Fix, FE

#286 Fix: 메모지 추가 버그 해결
  frontend/src/components/LogContainer/LogContainer.tsx
  frontend/src/pages/Test/components/Toolbar.tsx
Labels: ✨ Feat, 🐞 Fix, 🛠️ Refactor, FE

#289 Refactor(#288): Example 페이지 제거, 불필요한 routing 제거
  frontend/src/App.tsx
  frontend/src/components/Header/components/HeaderLoginButton.tsx
  frontend/src/components/Header/components/HeaderLogo.tsx
  frontend/src/pages/Example/Example.tsx
Labels: 🛠️ Refactor, FE

#287 Refactor: 미디어서버 HTTP Request 수정 및 백엔드 API 수정
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.service.ts
  mediaServer/src/RelayServer.ts
  mediaServer/src/utils/MediaConverter.ts
Labels: 🐞 Fix, 🛠️ Refactor, BE

#290 Feature(#244): 참여자 GUEST 타입 추가
  mediaServer/src/RelayServer.ts
  mediaServer/src/constants/client-type.constant.ts
  mediaServer/src/dto/serverAnswer.dto.ts
  mediaServer/src/services/participant.service.ts
Labels: ✨ Feat, BE

#295 Fix: 게스트 참여자 정상적으로 적용안되는 부분 수정
  mediaServer/src/RelayServer.ts
  mediaServer/src/models/FfmpegCommand.ts
  mediaServer/src/utils/MediaConverter.ts
Labels: 🐞 Fix, BE

#293 Fix: 수강목록 종료된 강의만 불러오기
  backend/src/user/user.service.ts
Labels: 🐞 Fix, BE

#297 Fix: NCP Object Storage에 mp3 파일 업로드 안되는 부분 수정
  mediaServer/src/models/FfmpegCommand.ts
  mediaServer/src/utils/MediaConverter.ts
  mediaServer/src/utils/ncp-storage.ts
Labels: 🐞 Fix, BE

#294 Fix: 프로그래스 바 마우스 다운 이벤트 발생 시 사라지는 버그 해결
  frontend/src/pages/Review/components/ProgressBar.tsx
Labels: 🐞 Fix, FE

#296 Fix: 토큰 만료된 사용자가 참여자 페이지에서 화이트보드를 볼 수 없는 문제 해결
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
Labels: 🔥 Hotfix, FE

#298 Feat: CLOVA 장문 음성추출 API 호출
  mediaServer/src/utils/MediaConverter.ts
Labels: ✨ Feat, BE

#299 Feature: 다시보기 완성
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/Review/Review.tsx
Labels: ✨ Feat, FE
