Repository boostcampwm2023/web13_Boarlog, pull requests merged in 2024-03, with the labels that each got.

#303 Refactor: 전반적인 미디어 서버 구조 개선
  mediaServer/.gitignore
  mediaServer/src/RelayServer.ts
  mediaServer/src/constants/message-type.constant.ts
  mediaServer/src/dto/server-answer.dto.ts
  mediaServer/src/listeners/client.listener.ts
  mediaServer/src/listeners/lecture.listener.ts
  mediaServer/src/main.ts
  mediaServer/src/models/ClientConnectionInfo.ts
  mediaServer/src/models/Message.ts
  mediaServer/src/repositories/client.repsitory.ts
  mediaServer/src/repositories/question-repository.ts
  mediaServer/src/repositories/room.repository.ts
  mediaServer/src/services/client.service.ts
  mediaServer/src/services/lecture.service.ts
  mediaServer/src/services/participant.service.ts
  mediaServer/src/services/presenter.service.ts
  mediaServer/src/services/socket.service.ts
  mediaServer/src/services/webrtc-connection.service.ts
  mediaServer/src/utils/media-converter.ts
  mediaServer/src/validation/client.validation.ts
  mediaServer/src/validation/lecture.validation.ts
  mediaServer/src/validation/request.validation.ts
Labels: 🛠️ Refactor, BE

#308 Refactor(#307): CLOVA API 호출 실패 시 재시도
  mediaServer/src/constants/clova-api-response-type.constant.ts
  mediaServer/src/dto/clova-api-request.dto.ts
  mediaServer/src/dto/clova-api-response.dto.ts
  mediaServer/src/utils/media-converter.ts
Labels: 🛠️ Refactor, BE

#315 Fix: disconnect된 클라이언트의 WebRTC connection이 해제되지 않는 문제 해결
  mediaServer/src/RelayServer.ts
  mediaServer/src/listeners/lecture.listener.ts
  mediaServer/src/models/RoomConnectionInfo.ts
Labels: 🐞 Fix, BE

#316 Refactor(#309): 화이트보드 정보를 압축해서 전송하도록 개선
  backend/src/lecture/dto/whiteboard-event.dto.ts
  backend/src/lecture/lecture.service.ts
  backend/src/lecture/schema/whiteboard-log.schema.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/dummy70.json
  frontend/public/reviewLecture.json
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/components/Header/components/HeaderParticipantControls.tsx
  frontend/src/pages/Participant/Participant.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/stores/stateParticipantCanvasInstance.ts
  frontend/src/utils/fabricCanvasUtil.ts
  mediaServer/src/types/canvas-data.interface.ts
Labels: 🛠️ Refactor, FE

#317 Refactor(#318): UserService 테스트코드 추가
  backend/package-lock.json
  backend/package.json
  backend/src/lecture/lecture.controller.ts
  backend/src/lecture/lecture.module.ts
  backend/src/lecture/lecture.service.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.spec.ts
  backend/src/user/user.service.ts
Labels: 🛠️ Refactor, BE

#322 Fix(#314, #321): 화이트보드 편집이 반영되지 않는 이슈
  frontend/src/components/Header/components/HeaderInstructorControls.tsx
  frontend/src/utils/fabricCanvasUtil.ts
  mediaServer/src/constants/client-status.constant.ts
  mediaServer/src/dto/room-info-request.dto.ts
  mediaServer/src/dto/room-info-response.dto.ts
  mediaServer/src/dto/server-answer.dto.ts
  mediaServer/src/listeners/client.listener.ts
  mediaServer/src/listeners/lecture.listener.ts
  mediaServer/src/main.ts
  mediaServer/src/models/ClientConnectionInfo.ts
  mediaServer/src/repositories/room.repository.ts
  mediaServer/src/services/lecture.service.ts
  mediaServer/src/services/presenter.service.ts
  mediaServer/src/services/socket.service.ts
  mediaServer/src/services/webrtc-connection.service.ts
  mediaServer/src/validation/client.validation.ts
  mediaServer/src/validation/lecture.validation.ts
Labels: 🐞 Fix, ALL
